import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 30,
    backgroundColor: "#1E2D24",
    minHeight: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 32,
    textAlign: "center",
    marginBottom: 18,
    color: "#FFD700", 
    fontWeight: "bold",
    letterSpacing: 2,
    textShadowColor: "#000",
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 3,
  },
  text: {
    fontSize: 16,
    color: "#e0e0e0",
    marginTop: 10,
    textAlign: "center",
  },
  cardRow: {
    height: 130,
    marginVertical: 8,
  },
  card: {
    width: 80,
    height: 120,
    resizeMode: "contain",
    marginHorizontal: 4,
    borderRadius: 6,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  result: {
    fontSize: 24,
    textAlign: "center",
    color: "#FFD700",
    marginVertical: 20,
    fontWeight: "bold",
    textShadowColor: "#000",
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 3,
  },
  button: {
    backgroundColor: "#27AE60",
    padding: 14,
    alignItems: "center",
    marginVertical: 10,
    borderRadius: 10,
    width: 220,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  buttonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  loadingText: {
    color: "#fff",
    fontSize: 18,
    marginTop: 10,
    textAlign: "center",
  },
});

export default styles;
