import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 30,
    backgroundColor: "#1E2D24", // verde escuro elegante
    minHeight: "100%",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  title: {
    fontSize: 32,
    textAlign: "center",
    marginBottom: 18,
    color: "#FFD700",
    fontWeight: "bold",
    letterSpacing: 2,
    textShadowColor: "#000",
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 3,
  },
  info: {
    fontSize: 16,
    marginBottom: 6,
    color: "#e0e0e0",
    textAlign: "center",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginVertical: 10,
    color: "#fff",
    textAlign: "center",
  },
  selectedCardBox: {
    backgroundColor: "#fafafa",
    padding: 14,
    marginVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    width: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  playButton: {
    backgroundColor: "#27AE60",
    padding: 14,
    alignItems: "center",
    marginVertical: 10,
    borderRadius: 10,
    width: 220,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  playButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  dealerTurnText: {
    textAlign: "center",
    fontSize: 16,
    color: "#FFB74D",
    marginVertical: 8,
    fontStyle: "italic",
  },
  message: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginVertical: 10,
  },
  messageGameOver: {
    color: "#E53935",
  },
  restartButton: {
    backgroundColor: "#2980B9",
    padding: 14,
    alignItems: "center",
    borderRadius: 10,
    marginTop: 12,
    width: 220,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  restartButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
  },
  dealerHandRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    minHeight: 80,
  },
  dealerCard: {
    width: 70,
    height: 100,
    marginHorizontal: 5,
    borderRadius: 6,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  playerHandRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
    minHeight: 80,
    width: "100%",
  },
  tableArea: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 24,
    minHeight: 120,
    width: "100%",
  },
});

export default styles;
